"""likes fix

Revision ID: 366095c45f69
Revises: 9929b874d23f
Create Date: 2023-11-26 07:05:01.000428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366095c45f69'
down_revision: Union[str, None] = '9929b874d23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_2', 'liked_songs', ['owner_id', 'song_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_2', 'liked_songs', type_='unique')
    # ### end Alembic commands ###
