"""likes r

Revision ID: 6f67b9d71ffe
Revises: 9388bfd87d89
Create Date: 2023-11-26 06:43:49.648350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f67b9d71ffe'
down_revision: Union[str, None] = '9388bfd87d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked_songs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_songs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('song_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='liked_songs_owner_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], name='liked_songs_song_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='liked_songs_pkey')
    )
    # ### end Alembic commands ###
