"""remove coverlink

Revision ID: 8c08b2009c67
Revises: 826e7a44d430
Create Date: 2023-11-14 06:36:11.345686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c08b2009c67'
down_revision: Union[str, None] = '826e7a44d430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'cover_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('cover_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
