"""playlists

Revision ID: 8e5fa48fd6b7
Revises: 6dba25c6c8a7
Create Date: 2023-11-20 01:48:48.954926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5fa48fd6b7'
down_revision: Union[str, None] = '6dba25c6c8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
