"""playlists

Revision ID: cd382f6659e4
Revises: f9cec790d8ad
Create Date: 2023-11-20 00:31:39.952848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd382f6659e4'
down_revision: Union[str, None] = 'f9cec790d8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_1', 'playlist_to_song', ['playlist_id', 'song_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_1', 'playlist_to_song', type_='unique')
    # ### end Alembic commands ###
